name: Flaky-check
on:
  workflow_dispatch:
jobs:
  get-flaky-test-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout idoft repo
      uses: actions/checkout@v2

    - name: Create emails.txt file
      run: printf 'dtorbett@gmu.edu\n%.0s' {1..100} > emails.txt

    - name: Test file
      run: head emails.txt

    - name: Get 5 old tests
      id: pr-output
      run: grep ,ID,,,$ pr-data.csv | grep -v \\[ | shuf --random-source=<(cat emails.txt) --buffer-size=1000000 | head -n 5
  
