name: Flaky-check
on:
  workflow_dispatch:
jobs:
  get-flaky-test-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout idoft repo
      uses: actions/checkout@v2

    - name: Create emails.txt file
      run: printf '${{ secrets.EMAIL }}\n%.0s' {1..100} > emails.txt

    - name: Get 5 old tests
      id: pr-output
      run: echo "PR_OUTPUT=$(grep ,ID,,,$ pr-data.csv | grep -v \\[ | shuf --random-source=<(cat emails.txt) --head-count=5)" >> $GITHUB_ENV

    - name: Test
      run: echo $PR_OUTPUT

    

  

    
  
