name: Flaky-check
on:
  workflow_dispatch:
jobs:
  get-flaky-test-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout idoft repo
      uses: actions/checkout@v2

    - name: Get 10 tests
      run: |
           grep ,ID,,,$ pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo {{ secrets.EMAIL }}; done) | head -n 5 && \
           grep ,ID,,,$ id-pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo {{ secrets.EMAIL }}; done) | head -n 5
