name: Flaky-check
on:
  workflow_dispatch:
jobs:
  flaky-test-without-nondex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        
    - name: Clone json-io
      uses: actions/checkout@v2
      with:
        repository: jdereg/json-io

    - name: Test without Nondex
      run: mvn test -Dtest=CollectionTests
        
    - name: Test with Nondex
      run: mvn edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=CollectionTests
  

    
  
