name: Flaky-check
on:
  workflow_dispatch:
jobs:
  get-flaky-test-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout idoft repo
      uses: actions/checkout@v2

    - name: Get 5 old tests
      id: pr-output
      run: echo "PR_OUTPUT=$(grep ,ID,,,$ pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo ${{ secrets.EMAIL }}; done) --head-count=5)" >> $GITHUB_ENV

    

  

    
  
